import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useEffect } from "react";

export default function Home({ apiQuotes }) {
  const [quote, setQuote] = useState("");

  const newQuote = () => {
    const randomNumber = Math.floor(Math.random() * apiQuotes.length);
    const randomQuote = apiQuotes[randomNumber];

    setQuote(randomQuote);
  };
  useEffect(() => {
    newQuote();
  }, []);

  return (
    <div>
      <Head>
        <title>Quote Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="quote-container" id="quote-container">
        <div className="quote-text">
          <i className="fas fa-quote-left"></i>
          <span id="quote">{quote.text}</span>
        </div>
        <div className="quote-author">
          {quote.author ? <span>{quote.author}</span> : <span>Unknown</span>}
        </div>
        <div className="button-container">
          <button className="twitter-button" id="twitter" title="Tweet this!">
            <i className="fab fa-twitter"></i>
          </button>
          <button onClick={newQuote} id="new-quote">
            New quote
          </button>
        </div>
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const apiUrl = "https://type.fit/api/quotes";
  const response = await fetch(apiUrl);
  let apiQuotes = await response.json();

  return {
    props: { apiQuotes },
  };
};
